### PR TITLE
epoll implements for non-linux OSs

### PR DESCRIPTION
**Pull request by mattn**
I don't have OSX. But maybe work.
Anyone, could you please check below?

```
$ cd lib
$ make clean all
$ cat io.c | ./a.out
```

### CODE REVIEW

**Comment by rhysd** [comment]
:+1:

I checked out this branch in OS X 10.9 and confirmed that `make` and `make test` succeeded.

**Comment by matz** [comment]
@mattn you are so incredible (and I feel I am old now).

**Comment by mattn** [comment]
Cooooool! :+1:

**Comment by suzukaze** [comment]
:+1

**Pull request merged**
