### PR TITLE
migrate to container based infrastructure for faster travis builds

### PR DESCRIPTION
**Pull request by markburns**
Based on http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

### CODE REVIEW

**Comment by markburns** [comment]
49s vs 9s

Doesn't look faster https://travis-ci.org/matz/streem/builds/92347574

Maybe because it is the first time? Can't see how to re-trigger a build in the UI though

**Comment by nicolasmccurdy** [comment]
If you have push access to the repo, you can re-trigger a build with the circular arrow button in the upper right of the build page.

**Comment by markburns** [comment]
Tried it now on my own fork on CI, definitely not faster

**Comment by matz** [comment]
Probably because current Streem tests are too small.  Try again when we have more meaningful test suites.

**Pull request closed without merging**
