### PR TITLE
Logos

### PR DESCRIPTION
**Pull request by nicolasmccurdy**
Please note that this is a work in progress which is open for discussion.

### CODE REVIEW

**Comment by matz** [comment]
I have no plan to integrate `|>` operator in Streem.  Maybe we should replace it by `|`.

**Comment by nicolasmccurdy** [comment]
`|` would also be used for bitwise OR, right? I feel like that could get confusing.

**Comment by matz** [comment]
That happens often, for example, + operator in Ruby (addition for numbers, concatenation for strings), >> operator in C++ (bit-shift for numbers, output for I/O).

**Comment by christopherdumas** [comment]
The `|>` conveys more flow though, as well as looking nicer, in my opinion.

**Comment by nicolasmccurdy** [comment]
Discussion continued in #57.

**Pull request closed without merging**
